name: Upload Existing Firmware

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-existing-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Write VERSION to version file
        run: python write_version.py

      - name: Check if Firmware and Version Files Exist Locally
        id: check_files
        run: |
          if [ -f ".pio/build/esp32-s3/firmware.bin" ] && [ -f ".pio/build/esp32-s3/version" ]; then
            echo "Firmware and version files exist. Proceeding with upload."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "Firmware or version file not found. Skipping upload."
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        if: env.exists == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Firmware and Version to S3 (Only if Changed)
        if: env.exists == 'true'
        run: |
          aws s3 sync .pio/build/esp32-s3/ s3://bpotaupdates/ --exact-timestamps

      - name: Output Firmware URL
        if: env.exists == 'true'
        run: |
          echo "Firmware uploaded to: https://bpotaupdates.s3.us-east-1.amazonaws.com/firmware.bin"
          echo "Version file uploaded to: https://bpotaupdates.s3.us-east-1.amazonaws.com/version"